### PR TITLE
Add zlib as an explicit dependency

### PR DESCRIPTION
**Pull request by Conan-Kudo**
It appears that the inclusion of libxml2 doesn't necessarily mean that zlib will be included. Since libcomps depends on zlib functions, the build fails when zlib isn't being brought in for the build.

This explicitly changes it to include zlib and ensure it is linked into the library at build-time.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
We don't use any of zlib functions in libcomps, so -1 from me/...

**Comment by j-mracek** [comment]
Please is it still relevant?

**Comment by Conan-Kudo** [comment]
@j-mracek yes, libcomps still doesn't compile on Mageia, OpenMandriva, and openSUSE without linking zlib... I don't know why this isn't required on Fedora, but is needed elsewhere.

**Comment by j-mracek** [comment]
Sorry for delay, but please can you rebase it?

**Comment by Conan-Kudo** [comment]
@j-mracek Done.

**Pull request merged**
